const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
const CHOOSE_LEVEL = 'CHOOSE_LEVEL';
const CHOOSE_TYPE = 'CHOOSE_TYPE';
const SET_COUNTRIES_LEVEL = 'SET_COUNTRIES_LEVEL';
const SET_QUIZ_QUESTOINS = 'SET_QUIZ_QUESTOINS';
const SET_ANSWER = 'SET_ANSWER';
const CHECK_ANSWER = 'CHECK_ANSWER';
const CHANGE_QUESTION = 'CHANGE_QUESTION';
const RESET_LEVEL = 'RESET_LEVEL';
const RESET_TYPE = 'RESET_TYPE';
const SET_NEXT_LEVEL = 'SET_NEXT_LEVEL';
const FINISH_QUIZ = 'FINISH_QUIZ';

export default {
  FETCH_COUNTRIES,
  CHOOSE_LEVEL,
  CHOOSE_TYPE,
  SET_COUNTRIES_LEVEL,
  SET_QUIZ_QUESTOINS,
  SET_ANSWER,
  CHECK_ANSWER,
  CHANGE_QUESTION,
  RESET_LEVEL,
  RESET_TYPE,
  SET_NEXT_LEVEL,
  FINISH_QUIZ,
};
