const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
const CHOOSE_LEVEL = 'CHOOSE_LEVEL';
const CHOOSE_TYPE = 'CHOOSE_TYPE';
const SET_COUNTRIES_LEVEL = 'SET_COUNTRIES_LEVEL';
const SET_QUIZ_QUESTOINS = 'SET_QUIZ_QUESTOINS';
const SET_ANSWER = 'SET_ANSWER';
const CHECK_ANSWER = 'CHECK_ANSWER';
const CHANGE_QUESTION = 'CHANGE_QUESTION';
const RESET_LEVEL = 'RESET_LEVEL';
const RESET_TYPE = 'RESET_TYPE';
const SET_NEXT_LEVEL = 'SET_NEXT_LEVEL';
const SET_FORM_TYPE = 'SET_FORM_TYPE';
const SET_CURRENT_ANSWER = 'SET_CURRENT_ANSWER';
const SET_ANSWERS = 'SET_ANSWERS';
const START_QUIZ = 'START_QUIZ';
const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
const SET_TIME = 'SET_TIME';
const REGISTER_USER = 'REGISTER_USER';
const CHECK_PASSWORD = 'CHECK_PASSWORD';
const SET_USER = 'SET_USER';
const SAVE_GAME = 'SAVE_GAME';
const RESET_FORM = 'RESET_FORM';
const SET_PLAYER_TO_DISPLAY = 'SET_PLAYER_TO_DISPLAY';

export default {
  FETCH_COUNTRIES,
  CHOOSE_LEVEL,
  CHOOSE_TYPE,
  SET_COUNTRIES_LEVEL,
  SET_QUIZ_QUESTOINS,
  SET_ANSWER,
  CHECK_ANSWER,
  CHANGE_QUESTION,
  RESET_LEVEL,
  RESET_TYPE,
  SET_NEXT_LEVEL,
  SET_FORM_TYPE,
  SET_CURRENT_ANSWER,
  SET_ANSWERS,
  START_QUIZ,
  SET_CURRENT_QUESTION,
  SET_TIME,
  REGISTER_USER,
  CHECK_PASSWORD,
  SET_USER,
  SAVE_GAME,
  RESET_FORM,
  SET_PLAYER_TO_DISPLAY,
};
